### ISSUE TITLE
Service Account Namespace

### ISSUE THREAD

**Issue by Skybound1** [FairwindsOps/rbac-lookup#178]
Hi guys, awesome tool! 

When running the tool, I notice that for service accounts it doesn't specify which namespace the service account lives in. This can cause confusion when you have service accounts in different namespaces sharing a name, especially if RBAC permissions are granted across namespace. So I was wondering whether it would be possible to update the output to include this information?

**Comment by sudermanjr** [comment]
The output of the service account name should show the namespace

```
▶ rbac-lookup ttl-controller
SUBJECT                       SCOPE          ROLE
kube-system:ttl-controller    cluster-wide   ClusterRole/system:controller:ttl-controller
```

note the `kube-system:ttl-controller` since that service account is in `kube-system`

**Comment by Skybound1** [comment]
:thinking: interesting, that namespace prefix doesn't appear for me... I wonder if this is PEBKAC and I just happen to be running a  old version without realising :joy: Lemme quickly check that

**Comment by Skybound1** [comment]
Right, this is  me running massively out of date... krew has 0.3.0 installed, and looking at releases latest is 0.6.4... although its weird that krew isn't updating it to 0.6.4 :thinking: I ended up just downloading the release... sorry about that, definitely PEBKAC

**Comment by sudermanjr** [comment]
Looks like we hadn't updated the krew index in a while. I just opened up a PR
