### ISSUE TITLE
permissions are too harsh IMO

### ISSUE THREAD

**Issue by georgettica** [FairwindsOps/rbac-lookup#195]
I can't always `list resource "rolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope`
and there is no `namespace` toggle I can set to limit it.

this was my hurdle in using the tool

my use case was finding connected roles and clusterroles connected to a serviceaccount

**Comment by lucasreed** [comment]
@georgettica Thanks for this report! To make sure I boil this down to a concrete feature request: You would like to see the option to pass `--namespace/-n <NAMESPACE>` to limit the required rbac permissions for using rbac-lookup, correct?

**Comment by georgettica** [comment]
yeah.. and maybe allow a toggle to `disable cluster check` so the default does what you started with doing?

what is the use case of taking the rolebindings on all clusters?
