### ISSUE TITLE
Warning message on Brew MacOS

### ISSUE THREAD

**Issue by sergirf** [FairwindsOps/rbac-lookup#209]
Good morning guys!

First of all, thanks for the cool tool, really useful, I appreciate so much your shared work 😉 .

The thing here is since I added your Tap to my Brew, any time I do any action with Brew (update, install, etc.) I get this warning:

`Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the fairwindsops/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/fairwindsops/homebrew-tap/Formula/rbac-lookup.rb:10`

I'm using a Macbook Pro (intel based) and now I'm in MacOS Monterey 12.2 but this was happening also with Big Sur 11.X.

It's just a warning, so everything works fine but it would be nice if we can get rid of it.

Once again, thanks 🙇 !

**Comment by lucasreed** [comment]
:wave: Hey @sergirf, thanks for the report! I do know we've fixed most of these Homebrew issues but there are a couple more formulas that still have `bottle :unneeded` in there. It looks like rbac-lookup and polaris, so we'll work on getting goreleaser updated in these projects which is what populates those files for us.

Thanks again!

**Comment by lucasreed** [comment]
Two PRs created for this:

[rbac-lookup](https://github.com/FairwindsOps/rbac-lookup/pull/210)
[polaris](https://github.com/FairwindsOps/polaris/pull/700)
