### ISSUE TITLE
v0.8.1 does not run under bare ubi8/ubi

### ISSUE THREAD

**Issue by Nuru** [FairwindsOps/rbac-lookup#220]
### What happened?

Running in Docker container `registry.access.redhat.com/ubi8/ubi` (described [here](https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e)):

```bash
$ ls -l /usr/bin/rbac-lookup 
-rwxr-xr-x 1 root root 29999104 Feb 21 03:38 /usr/bin/rbac-lookup
$ /usr/bin/rbac-lookup
bash: /usr/bin/rbac-lookup: No such file or directory
```

This is almost certainly caused by enabing `CGO` in #213

### What did you expect to happen?

```bash
$ rbac-lookup 
Error getting Kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### How can we reproduce this?

```bash
$ docker run --rm -it registry.access.redhat.com/ubi8/ubi bash
[root@758dbf441bb8 /]# curl -sSL https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.8.1/rbac-lookup_0.8.1_Linux_x86_64.tar.gz | tar -xz
[root@758dbf441bb8 /]# ls -l ./rbac-lookup 
-rwxr-xr-x 1 root root 29999104 Feb 10 20:12 ./rbac-lookup
[root@758dbf441bb8 /]# ./rbac-lookup 
bash: ./rbac-lookup: No such file or directory
[root@758dbf441bb8 /]# 
```

### version

0.8.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

`CGO=enabled` requires dependent libraries to already be installed on the target machine. Obviously some library is missing in Red Hat.

Note that `CGO` was enabled in #213 to fix #206 but [it did not, in fact, fix #206](https://github.com/FairwindsOps/rbac-lookup/issues/206#issuecomment-1038307637)

**Comment by sudermanjr** [comment]
I was able to reproduce this, and I can validate that re-enabling CGO does in fact fix the issue. I think reverting that change might be the correct solution until we have further info on #206 and how to fix the DNS issues
