### ISSUE TITLE
Investigate AKS/EKS compatibility

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/rbac-lookup#23]

**Comment by tklovett** [comment]
I've been using rbac-lookup occasionally (and rbac-manager) on EKS for a couple months. I haven't come across any EKS-related problems or gotchas. 👍

**Comment by sudermanjr** [comment]
> I've been using rbac-lookup occasionally (and rbac-manager) on EKS for a couple months. I haven't come across any EKS-related problems or gotchas. 👍

@tklovett Thanks for the info!

**Comment by sudermanjr** [comment]
- [ x ] EKS
- [ ] AKS
