### ISSUE TITLE
[FEAT]: make `lookup` directory a public pkg to be imported in golang projects

### ISSUE THREAD

**Issue by mritunjaysharma394** [FairwindsOps/rbac-lookup#232]
**Is your feature request related to a problem? Please describe.**
Thanks a lot for building this amazing project! I would love to give you suggestion if you
can make available `lookup` as a public `pkg` that can be imported in other golang projects to use
`lister` facility of getting Roles and Cluster Roles. An example use-case is this
[issue ](https://github.com/kyverno/kyverno/issues/3177) where we intend to use it to solve it  

**Describe the solution you'd like**
I would like `lookup` directory as a public `pkg` (or at least parts of it so that we can import it and re-use it)

**Describe alternatives you've considered**
An alternative is to use the portions of existing code to build something like lookup package to get Roles and ClusterRoles but I think that might not be a good practice, what do you suggest? 

**Additional context**
None

**Comment by sudermanjr** [comment]
This seems fine to me. I would be happy to take a look at a PR for this. Naturally the functionality of this tool is top priority for our use, so as long as that doesn't change I'm good with it.
