### ISSUE TITLE
Add support for --kubeconfig parameter to specify a config file

### ISSUE THREAD

**Issue by shouah** [FairwindsOps/rbac-lookup#28]
Description:
this tool expects and can only use the default configuration located at $HOME/.kube/config

Request:
Enhance the tool to follow the kubect CLIl-based approach of supporting a --kubeconfig parameter to specify an alternative config file. This allows seamless support for switching among multiple configuration files.

**Comment by sudermanjr** [comment]
@shouah Thanks for bringing this to our attention.  We will take a look at adding the `--kubeconfig` flag.  In the meantime, you can use the environment variable `$KUBECONFIG` to set a different kubeconfig if you wish to utilize multiple files.

**Comment by sudermanjr** [comment]
This was fixed in https://github.com/FairwindsOps/rbac-lookup/pull/38
