### ISSUE TITLE
Display permission details

### ISSUE THREAD

**Issue by jglick** [FairwindsOps/rbac-lookup#29]
Currently this tool displays _roles_ (incl. cluster roles), but not what actual permissions are granted from them. To see what I mean, try something like

```sh
kubectl rbac-lookup $account -o role | tail +2 | awk '{print $3}' | xargs kubectl describe
```

but mentally take the union of those permissions when there are overlapping roles (or cluster roles).

I would like to see something that would display columns with resources, verbs, etc. like `kubectl describe` provides, as well as columns displaying the role(s) and binding(s) that contributed to those permissions, so that I could see all the permissions available to a given service account or user in one table.

**Comment by sudermanjr** [comment]
I agree with @robscott  on this one.  I think rakkess covers the request here.
