### ISSUE TITLE
Having issues with kubectl 1.23 client version

### ISSUE THREAD

**Issue by pmady** [FairwindsOps/rbac-lookup#305]
### What happened?

Installed rbac-lookup with krew and which running , was having issue as below
 ```
kubectl rbac-lookup
Error generating Kubernetes clientset from kubeconfig: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```
I am having kubectl version as
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### What did you expect to happen?

Work normally as expected, not able to run any 
`kubectl rbac-lookup `command

Does it need kubectl client higher verison. If so, is there any document says the compatibility matrix with kubectl version?

### How can we reproduce this?

Have kubectl client 1.23.6

### Version

latest

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Not sure if this is related, but I don't think kubectl 1.23 is supported when your cluster version is 1.21. I can take a look at the client-go versions we have currently and see if we need an update though. 

We don't typically maintain a compatibility matrix.

**Comment by sudermanjr** [comment]
@pmady if you want to try building from #306 with the dependencies updated, that might work.

**Comment by sudermanjr** [comment]
Or try the just-release v0.10.0 :-D
