### ISSUE TITLE
Review and make changes to CONTRIBUTING.md

### ISSUE THREAD

**Issue by kimschles** [FairwindsOps/rbac-lookup#41]
Some instructions in the CONTRIBUTING doc don't work. 
* `make` commands aren't working for me locally 
* The link to sign the CLA is broken. 

Go through the instructions in this doc, and if they don't work, figure out what does and make changes as needed.

**Comment by sudermanjr** [comment]
@ejether should be able to help with the CLA issues.

**Comment by sudermanjr** [comment]
> * `make` commands aren't working for me locally

There are some dependencies that are required for some of the Make commands to work. I think golint is the primary one. This is probably missing from the documentation :-D
