### ISSUE TITLE
Use krew-release-bot for publishing plugin releases

### ISSUE THREAD

**Issue by rajatjindal** [FairwindsOps/rbac-lookup#48]
I have created [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) to auto publish new plugin releases to krew-index repo. 

If its ok with rbac-lookup authors, I can open a PR to start using that for auto publishing the releases or you can look at the [circleci](https://github.com/rajatjindal/krew-release-bot/blob/master/examples/circleci.yml) example here, and configure it.

Many thanks for considering.
Rajat Jindal

**Comment by sudermanjr** [comment]
@rajatjindal Thanks for asking! I will have to take a look a little bit more and talk to the other codeowners.

**Comment by rajatjindal** [comment]
sure @sudermanjr . Looking forward to your feedback. Happy to answers any questions you might have.

**Comment by sudermanjr** [comment]
I will add this to our internal roadmap for the project. Thanks for the suggestion!
